[mcp_servers.filesystem]
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "source/images",
    "source/diagrams",
]
command = "npx"

[mcp_servers.github]
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]
command = "npx"
env_vars = ["GITHUB_TOKEN"]
