@startmindmap
+ 商品信息

-- 1.基础信息（spu,basic info）
--- 商品ID
--- 类目
--- 品牌
--- 商品状态(on_sale, off_sale, deleted, frozen)
--- 商品名称
--- 商品标题
--- 商品描述
--- 商品展示图，视频，3D展示
--- 标签信息/商品标签/营销标签人群标签
--- 商品属性 （spu attribute）
---- 材质
---- 产地
---- 生产日期
---- 保质期

-- 2.规格信息(SKU)
--- 规格属性（sale attribute）
---- 颜色
---- 尺寸
---- 虚拟商品（面额，quota,有效期等）
--- 价格信息、销售价格、原价、促销价
--- 库存信息、库存类型、库存数量、库存位置

++ 3.统计信息
+++ 销售数据
+++ 评分
+++ 运营数据。浏览量、收藏数、加购数、分享数

++ 4.商品快照
+++ 价格快照
+++ 历史价格
++ 商品操作日志

++ 5.营销信息
+++ 促销活动
+++ 优惠券
+++ 会员权益

++ 6.物流信息
+++ 配送信息
+++ 仓储信息
+++ 包装信息


@endmindmap