
@startmindmap
* Programmer's Workplace Survival Guide
** 终身学习与知识管理
*** 学习方法: What learning methods work for top students?
*** 学习能力: Why do some people learn better and faster than others?
*** 学习心态: Is perseverance or mindset more important in learning?
*** 学习本质: What is truly learned when we "study"?
*** 终身学习: How can we continue to improve after starting work?

*** 技术学习（Technical Skills）
**** 内功修炼: What core skills are essential to becoming a technical expert?
**** 编程能力: How can one become a standout programmer despite customer ignorance?
**** 架构能力: Why do some people have a better grasp of architecture than others?
**** 迭代能力: How can I develop faster than my peers?
**** 业务能力: Is it important for technical people to understand business deeply?
**** 真的读过哪些书籍(3遍以上)？
**** 认真读过哪些优秀源码？
**** 真的学过哪些课程？
**** 做过哪些值得介绍的项目，遇到哪些挑战？

*** Interviews
**** 简历筛写: How do I make my resume stand out?
**** 算法面试: leetcode
**** 技术面试: 技术 + 项目 + 系统设计 + 管理
**** HR面试: How can I pass HR interviews?

*** 知识管理
**** blog维护
*** 英语学习

**  工作Work
*** 成事能力: What qualities make a person most likely to succeed?
*** 技术成长: How can one grow technically without having strong projects?
*** 沟通能力: "Talk is cheap, show me the code"?
*** 做事原则: What are the principles for succeeding in a complex company?
*** 至暗时刻: How to survive the toughest times in your career?

*** Career Planning
**** 职业规划: Feeling lost in your career, what should you do?
**** 知识规划: What knowledge should you invest in over your lifetime?
**** 机会选择: Why do some people catch opportunities while others miss them?
**** 长远规划: How should I balance short-term and long-term career goals?
**** 中年危机: How do programmers overcome midlife crises in their 35s?

*** Job-Hopping
**** 跳槽动机: Is hopping jobs really for a salary increase?
**** offer选择: How to choose between multiple offers?
**** 大厂之路: Why can't I get into big companies?
**** 学历困局: How to deal with poor academic qualifications in a competitive environment?

*** Promotion
**** 晋升路线: What skills are necessary to stand out in promotion pathways?
**** 晋升管理: Why is it hard to get promoted, even with excellent performance?
**** 晋升僵局: What should I do if promotion seems blocked?


** Management
*** 认识管理: Why do I recommend the technical management path?
*** 深入之术: How to become a qualified technical manager?
*** 向上管理: How can I get my leaders to support me?

left side

** 副业和创业（Side Business）
*** 第二职业: What traits do programmers need when starting a side business?
*** 方向选择: How to choose the right side business?
*** 转变思维: What mindset shift is required for a programmer to succeed in entrepreneurship?
*** 创业难题: What are the key factors to address in starting a business?


** 心态(Mindset)
*** 勇于尝试: How to find more opportunities by being bold?
*** 拒绝拖延: How to overcome procrastination for higher productivity?
*** 适应时代: How to stay competitive in the era of big data and AI?
*** 接受平凡: Why do people choose to settle, and is it the right path?
@endmindmap
